//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class eser
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public eser()
    {
        this.sanatci = new HashSet<sanatci>();
    }

    public int eser_id { get; set; }
    public string eser_adi { get; set; }
    public byte[] eser_foto { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<sanatci> sanatci { get; set; }
}

public partial class sanatci
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public sanatci()
    {
        this.sergi = new HashSet<sergi>();
    }

    public int sanatci_id { get; set; }
    public string sanatci_adi { get; set; }
    public string sanatci_bilgi { get; set; }
    public int eser_id { get; set; }

    public virtual eser eser { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<sergi> sergi { get; set; }
}

public partial class sergi
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public sergi()
    {
        this.yorum = new HashSet<yorum>();
    }

    public int s_id { get; set; }
    public string s_adi { get; set; }
    public string s_tarih { get; set; }
    public string s_bilgi { get; set; }
    public int sanatci_id { get; set; }
    public byte[] s_resim1 { get; set; }
    public byte[] s_resim2 { get; set; }
    public int s_guncel { get; set; }

    public virtual sanatci sanatci { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<yorum> yorum { get; set; }
}

public partial class yorum
{
    public int yorum_id { get; set; }
    public string yorum_user { get; set; }
    public string yorum_yorum { get; set; }
    public string yorum_tarih { get; set; }
    public Nullable<int> s_id { get; set; }

    public virtual sergi sergi { get; set; }
}
