//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class sanatEntities : DbContext
{
    public sanatEntities()
        : base("name=sanatEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<eser> eser { get; set; }
    public virtual DbSet<sanatci> sanatci { get; set; }
    public virtual DbSet<sergi> sergi { get; set; }
    public virtual DbSet<yorum> yorum { get; set; }
}
